-- Supabase Database Setup for Almuheet Accounting System
-- Run this in Supabase SQL Editor

-- Drop existing tables if they exist (clean start)
DROP TABLE IF EXISTS almuheet_activity CASCADE;
DROP TABLE IF EXISTS almuheet_users CASCADE;
DROP TABLE IF EXISTS almuheet_files CASCADE;
DROP TABLE IF EXISTS almuheet_data CASCADE;

-- Create almuheet_data table (main data table)
CREATE TABLE almuheet_data (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create almuheet_files table (archive files table)
CREATE TABLE almuheet_files (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  file_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create almuheet_users table (users table)
CREATE TABLE almuheet_users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  users JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create almuheet_activity table (activity log table)
CREATE TABLE almuheet_activity (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  activity JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE almuheet_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE almuheet_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE almuheet_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE almuheet_activity ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public access (for anon key usage)
CREATE POLICY "Allow public access to almuheet_data" 
ON almuheet_data FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to almuheet_files" 
ON almuheet_files FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to almuheet_users" 
ON almuheet_users FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to almuheet_activity" 
ON almuheet_activity FOR ALL USING (true) WITH CHECK (true);

-- Create indexes for better performance
CREATE INDEX idx_almuheet_data_updated_at ON almuheet_data(updated_at DESC);
CREATE INDEX idx_almuheet_files_updated_at ON almuheet_files(updated_at DESC);
CREATE INDEX idx_almuheet_users_updated_at ON almuheet_users(updated_at DESC);
CREATE INDEX idx_almuheet_activity_updated_at ON almuheet_activity(updated_at DESC);

-- Insert initial empty records (id=1) for each table
INSERT INTO almuheet_data (id, data) 
VALUES (1, '{}'::jsonb);

INSERT INTO almuheet_files (id, file_data) 
VALUES (1, '[]'::jsonb);

INSERT INTO almuheet_users (id, users) 
VALUES (1, '[]'::jsonb);

INSERT INTO almuheet_activity (id, activity) 
VALUES (1, '[]'::jsonb);
